Login page
digjao/Projeto-Rifa pull request #1
Opened 2024-05-14 15:38 UTC by digjao

2024-05-15 12:18 UTC, medina325 requested changes

2024-05-15 12:18 UTC, medina325 commented on index.html
> +    <link rel="preconnect" href="https://fonts.googleapis.com">
Já está usando cada um desses caras?
- https://fonts.googleapis.com
- https://fonts.gstatic.com
- https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap

2024-05-15 12:18 UTC, medina325 commented on src/components/Login.tsx
> +            <input type="text" id="username" className="border-b-2 border-black w-full text-xl px-2 py-1 focus:outline-none focus:ring-0 focus:border-gray-600 mb-5 bg-[#EFEFEF] " placeholder="Senha">
O atributo `type` deveria ser "password" e não "text".

![image](https://github.com/digjao/Projeto-Rifa/assets/56964034/f5afa72d-4f7e-4b45-b12c-c2b71b3ee8d4)

2024-05-15 12:18 UTC, medina325 commented on src/components/Login.tsx
> +                <h1 className="mb-4">Logar com google</h1>
Blz falta ainda colocar o ícone do Google e do Facebook.

2024-05-15 12:18 UTC, medina325 commented on src/components/Login.tsx
> +            <button type="submit" className="border-2 bg-indigo-700 text-white rounded-md py-1 w-48 text-xl border-black">Login</button>
Configura a cor roxa definida nos mockups ao invés desse bg-indigo-700.

2024-05-15 12:18 UTC, medina325 commented on src/components/Login.tsx
> +            <a href="#" className="text-indigo-900 ml-2 underline">inscreva-se</a>
Deveria ser "Inscreva-se" e não "inscreva-se".

2024-05-15 12:18 UTC, medina325 commented on src/components/Login.tsx
> +            <a href="#" className="text-indigo-900 ml-2 underline">inscreva-se</a>
Também seria legal que não tivesse sublinhado padrão de tags `a` (tem uma propriedade CSS que estiliza isso) .
E a cor do texto deveria ser o roxo dos mockups.

![image](https://github.com/digjao/Projeto-Rifa/assets/56964034/77c10509-34d6-434b-85ec-3a3a63775ab8)

2024-05-15 12:18 UTC, medina325 commented on src/components/Login.tsx
> +              <a href="#" className="font-semibold">Esqueceu a senha?</a>
Mesma observação que deixei para o link do "Inscreva-se" mais pra baixo.

2024-05-15 13:06 UTC, medina325 commented on tailwind.config.js
> +            'bluezinho':'color:blue'
teste

2024-05-15 13:07 UTC, medina325 commented on tailwind.config.js
> +            'bluezinho':'color:blue'
teste

2024-05-15 13:19 UTC, digjao commented on src/components/Login.tsx
> +            <input type="text" id="username" className="border-b-2 border-black w-full text-xl px-2 py-1 focus:outline-none focus:ring-0 focus:border-gray-600 mb-5 bg-[#EFEFEF] " placeholder="Senha">
ne kkk e o id tbm... eu acho q copiei a linha do input inteiro pra economizar tempo e esqueci de mudar

2024-05-15 14:57 UTC, medina325 requested changes

2024-05-15 14:57 UTC, medina325 commented on src/components/Login.tsx
> +                <h1 className="mb-4">Logar com google</h1>
Deveria ser Google e não google 😠

2024-05-15 14:57 UTC, medina325 commented on src/components/Login.tsx
> +            <input type="text" id="username" className=" border-b-2 border-black w-full text-xl px-2 py-1 focus:outline-none focus:ring-0 focus:border-gray-600 mb-5 bg-[#EFEFEF]" placeholder="Email o
é muito complicado criar aquele efeito em que o placeholder vai para cima em uma fonte menor quando o input é clicado?

2024-05-15 14:57 UTC, medina325 commented on src/components/Login.tsx
> +            <div>
Muito complicado centralizar verticalmente os elementos nesse div?

2024-05-15 14:57 UTC, medina325 commented on src/components/Login.tsx
> +            <a href="#" className="text-[#7B66FD] ml-2">Inscreva-se</a>
Talvez bold fosse mais interessante, oq acha?

2024-05-15 15:03 UTC, digjao commented on src/components/Login.tsx
> +            <div>
centralizar os inputs verticalmente? ja nao estao?

2024-05-15 17:42 UTC, digjao commented on src/components/Login.tsx
> +            <input type="text" id="username" className=" border-b-2 border-black w-full text-xl px-2 py-1 focus:outline-none focus:ring-0 focus:border-gray-600 mb-5 bg-[#EFEFEF]" placeholder="Email o
cara... é um pouco, vai entrar um trilhao de propriedades nesses divs do input, e tem que implementar tbm alguns JS pra poder fazer... mas putz, pra mim ta massa do jeito q ta... minimalista e tals

2024-05-15 17:42 UTC, digjao commented on src/components/Login.tsx
> +                <h1 className="mb-4">Logar com google</h1>
kkk vei a gente vai mudar isso pra um botao futuramente

2024-05-16 14:59 UTC, medina325 approved these changes

2024-05-16 14:59 UTC, merged