Esboçando o componente de criar rifa
digjao/Projeto-Rifa pull request #5
Opened 2024-06-19 18:36 UTC by digjao

2024-06-23 00:09 UTC, medina325 requested changes

2024-06-23 00:09 UTC, medina325 commented on src/components/CriarRifa.tsx
> +                                <input type="text" className="border-2 border-black p-2 rounded-3xl" placeholder="Ex: 99/99/9999"/>
Poderia usar um type="date" aqui.

2024-06-23 00:09 UTC, medina325 commented on src/components/CriarRifa.tsx
> +                                <input type="text" className="border-2 border-black p-2 rounded-3xl" placeholder="Ex: R$0,00"/>
Poderia usar type="number" e step="0.01"

2024-06-23 00:09 UTC, medina325 commented on src/components/CriarRifa.tsx
> +                <h1>Faça um upload da foto para confirmar o seu objetivo da rifa, isso transmite mais veracidade e consegue adquirir mais recursos para sua rifa.</h1>
Poderia usar uma lista `<ul>` aqui ao invés de h1s

2024-06-23 00:09 UTC, medina325 commented on src/components/NavBar.tsx
> +          <button type="submit" onClickCapture={novaRifa} className="w-96 mr-20 border-2 bg-[#7B66FD] text-white rounded-md py-1 text-3xl border-black">Criar Rifa</button>
Observando bem, o texto deveria ser `Criar nova rifa` e não `Criar Rifa` kkkkkk
a dona Lia ficou confusa ahahahaha

2024-06-24 12:19 UTC, digjao commented on src/components/CriarRifa.tsx
> +export const CriarRifa = () => {
vixi, será q esqueci do wrap? dps me manda um print de tela cheia

2024-06-24 12:49 UTC, digjao commented on src/components/CriarRifa.tsx
> +export const CriarRifa = () => {
ve agora... apliquei 3 propriedades novas

2024-07-01 12:12 UTC, medina325 commented on src/components/CriarRifa.tsx
> +export const CriarRifa = () => {
nossa ficou muito melhor

2024-07-01 12:14 UTC, merged